# Generated by Django 5.1.1 on 2024-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
